### ISSUE TITLE
Reflection in your code base

### ISSUE THREAD

**Issue by stef-ang** [ErickSumargo/Dads#83]
Hei Erick, it's nice project, you're implementing a lot of latest libraries and best practices. But I spotted a reflection when you accessed the `MainActivity` from `feature_home`. We have ideas to improve it, maybe we can implement either a BroadcastReceiver or Dependency Inversion. Which one do you prefer?

**Comment by ErickSumargo** [comment]
Yeah planned to refactor it as well. Btw, nice catch!

Ok, let's continue upon your submitted PR. Thx!
